name: Permanent APK Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gops9/buildozer:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK with Pre-configured Buildozer
        run: |
          buildozer android debug
